services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "18000:8000"
    volumes:
      - ./output:/app/output:rw
      - ./backend:/app/backend:ro
      - ./backend/logs:/app/logs:rw
      - ./tests:/app/tests:ro
    environment:
      - PYTHONPATH=/app
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=8000
      - LOG_LEVEL=DEBUG
      - CORS_ORIGINS=*
    restart: unless-stopped
    networks:
      - scraper-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    user: "1000:1000"
    command: ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      - VITE_API_BASE_URL=http://localhost:18000
      - NODE_ENV=development
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - scraper-network
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

  test:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./tests:/app/tests
      - ./output:/app/output:rw
      - ./backend:/app/backend:ro
    environment:
      - PYTHONPATH=/app
    user: "1000:1000"
    command: >
      sh -c "
        echo 'Waiting for backend to be ready...' &&
        while ! curl -f http://backend:8000/api/health > /dev/null 2>&1; do
          echo 'Backend not ready, waiting...' &&
          sleep 2
        done &&
        echo 'Backend is ready! Running tests...' &&
        python -m pytest tests/ -v --tb=short
      "
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - scraper-network

networks:
  scraper-network:
    driver: bridge

volumes:
  output: 